# Generated by Django 3.0.5 on 2020-05-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cadastra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastra',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='Não informado', max_length=45, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nm_mae',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nome da mãe'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nr_rg',
            field=models.CharField(default=True, max_length=15, verbose_name='Numero do RG'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dsc_complemento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nr_endereco',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
